site_name: Matheus Bongiorno
site_author: Matheus Bongiorno
site_description: Blog pessoal, aqui aonde vou compartilhar sobre tecnologias e vivência profissionais

repo_name: https://github.com/matheus-bongiorno


# Page tree
nav:
    - Início: index.md
    - Java: java.md    
        #- setup/index.md
    #-- Python: 
       #-- Sring: python_string.md
       #-- Number: python_number.md
       #-- Method: python_method.md


# Configuration
theme:
    name: material
    palette:
        primary: deep orange
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.tabs
        - navigation.tabs.sticky

  
    
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde